### ISSUE TITLE
[Code] Preprocessing code for LVC-VC 

### ISSUE THREAD

**Issue by hcy71o** [wonjune-kang/lvc-vc#4]
Thank you for your interesting research. I was wondering if you have any code related to [lifting in the Quefrency domain] mentioned in the paper. If I'm not mistaken, there seems to be only preprocessing code for LVC-VC-XL (wav2vec2.0). If it is not disclosed, I'd be grateful to know the source you referenced in your implementation for preprocessing LVC-VC.

**Comment by wonjune-kang** [comment]
Hello! The low-quefrency liftering is done directly in the dataloader in [dataset.py](https://github.com/wonjune-kang/lvc-vc/blob/main/dataset.py) rather than being part of the preprocessing pipeline because it has a fairly low computational cost. Please see the function [lowquef_lifter](https://github.com/wonjune-kang/lvc-vc/blob/main/utils/utils.py#L26) in utils/utils.py for more details.

**Comment by hcy71o** [comment]
> Hello! The low-quefrency liftering is done directly in the dataloader in [dataset.py](https://github.com/wonjune-kang/lvc-vc/blob/main/dataset.py) rather than being part of the preprocessing pipeline because it has a fairly low computational cost. Please see the function [lowquef_lifter](https://github.com/wonjune-kang/lvc-vc/blob/main/utils/utils.py#L26) in utils/utils.py for more details on the actual implementation.

Thank you for kind explanation!
